### ISSUE TITLE
Send the Email address to LogRocket so we can identify sessions.

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#109]

**Comment by markalolo** [comment]
Documentation:
https://docs.logrocket.com/reference/identify

**Comment by linearcombination** [comment]
@markalolo How do you want users identified if they don't provide an email? Are you ok with anonymous user sessions that simply are tied to a UID in the case where email is not provided?

**Comment by markalolo** [comment]
Yes, that's fine. Thanks!

**Comment by markalolo** [comment]
I moved this back to In Progress. I noticed a few issues.

1. If I put in an email address, then go off to pick languages, when I return to the home screen my email address is gone.
2. Sessions aren't picking up the email address as an identifier. I've tested this and I can see the email address on the session replay, but the session still shows as anonymous.
3. LogRocket is complaining about this:
"LogRocket has already been loaded, loading a second instance is not supported. This is often caused by loading LogRocket as a package in your application and as a script tag."
Every time that a session returns to the home screen.

**Comment by linearcombination** [comment]
Thanks for the heads up, I'll check it out.

**Comment by markalolo** [comment]
I'm seeing user IDs of the email in LogRocket! That's awesome. I'm no longer seeing any anonymous sessions though, nor am I seeing any sessions from the Production site. I'm not sure exactly what's going on - do you have any thoughts?

**Comment by linearcombination** [comment]
I think I know what is going on. I'll have a fix for it soon. Thanks for bringing it to my attention.
