### ISSUE TITLE
Bible Commentary not working in English

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#111]
I've tested Bible Commentary a couple times in English, specifically for 1 & 2 Thes, and Matthew and it failed with an error.

**Comment by markalolo** [comment]
["taskId in poll: dfe0376c-95e5-4373-8ccf-45369ce90a95"]

and 

["taskId in poll: 0060a7df-3a6b-4e7f-b8ee-28fbb63da7c8"]

**Comment by linearcombination** [comment]
A fix has been deployed if you would like to try it.
