### ISSUE TITLE
Move the Email address to the Content page so that users are more likely to include their Email address and we can follow up with them.

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#112]

**Comment by linearcombination** [comment]
@markalolo Here is how it looks with email on the Home/Content page rather than the Settings page. What do you think? To me it looks suboptimal, but I totally get why you want it of course. I can move forward with it if you like.

![image](https://github.com/WycliffeAssociates/DOC/assets/68243616/67f0f9f9-54dc-4875-8da2-7146a4e6cffb)

**Comment by markalolo** [comment]
How about this instead?

![IRG UI with email](https://github.com/WycliffeAssociates/DOC/assets/12574715/03554aa5-5607-40dc-8cdf-92987e4dd1c8)

**Comment by linearcombination** [comment]
@markalolo Thanks for creating the image. That is actually what I had at first but then I realized that the user would likely fill out the email after first choosing Languages, Books, and Resource Types which would mean those three actions would have no email associated with them in LogRocket which would make the situation almost exactly analogous to having email on Settings page as far as tracking in LogRocket.

**Comment by markalolo** [comment]
@linearcombination LogRocket doesn't care when a user gets identified. If the email address comes in at any point in the user session, it will be the user ID for all the recorded actions. It's not problem if it happens later in the session.

**Comment by linearcombination** [comment]
@markalolo Oh that’s cool. Ok, I will put the email address where your picture shows then (and where I had it initially). Thanks!
