### ISSUE TITLE
Reduce Translation Words to just the words that appear within the given book

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#116]
As a translator who is considering printing out scripture and Words, I would like to have only the Words that appear in the given scripture be part of the document, so that my document will be as short as possible.

**Comment by linearcombination** [comment]
This will be a fun task and fairly complex to accomplish but involve a few cool compsci concepts. I am keen to get started on it as it will take a while to complete.  So if you want to approve this I will get started on it.

**Comment by linearcombination** [comment]
I found this note I wrote in the source around TW handling that is useful to consider:

"        # NOTE Another approach to including translation words would be to
        # only include words in the translation section which occur in current
        # lang_code, book content. The problem with this is that translation note
        # 'See also' sections often refer to translation words that are not part
        # of the lang_code/book content. In other words, by limiting the translation 
        # words we limit the ability of those using the interleaved document to gain
        #  deeper understanding of the interrelationships of words.
"
Having shorter documents may be more important than this consideration, but I thought I would put it out there as it does represent a degradation in the usefulness of the TW resource. Again, glad to implement this, but good to do it knowing what a translator loses when we do this.

**Comment by linearcombination** [comment]
I thought about this for a bit and then, due to the nice architecture we have, was able to implement it very quickly.  I apologize for going ahead, but it was a fun problem to solve. If you move it to approved then I'll deploy a PR for it. I implemented it so that it is toggle-able at the configuration level, so if you want it you just change one boolean in a config file and if you don't you can turn it off and get all the TWs.

**Comment by markalolo** [comment]
Lang, that sounds great. Let's go ahead and deploy it to the Dev environment. Would it be possible to make active/deactivating it part of the API call? So that a user could select it when generating the document?

**Comment by linearcombination** [comment]
Yes, that is something we can do. Do you want it exposed on the Settings page in the UI too as a toggle switch?

**Comment by markalolo** [comment]
Yes, I think a toggle would be good. A toggle for most of the options would be good -- I'd like to include that in our future designs.

**Comment by markalolo** [comment]
This one is also not functional in the Dev environment. I will stop trying to test until the question of deployment is solved.

**Comment by markalolo** [comment]
Tested and approved. It works great!
