### ISSUE TITLE
UI redesign

### ISSUE THREAD

**Issue by linearcombination** [WycliffeAssociates/DOC#124]
Several product owner originating requirements indicate that a UI redesign is in order. 

Topics: 

- Different flow/screens
- toggles for settings: which and how many are too many for full/experimental version
- etc..

Considerations:

- Would be a good idea to come up with low-fi hand-drawn screen mockups to test new flow and layout ideas
- Potentially involve UI designer in update if available and necessary (to be determined); we might be ok without, depends on nature of proposed changes

**Comment by linearcombination** [comment]
@markalolo , @PurpleGuitar , @abycurley  Can you please indicate specific things that you would like changed in the UI that would make the experience better? I would like to work on such improvements this next week. It doesn't have to be exhaustive, we can start with one or two improvements that really would make the UI less annoying for you or that you think would make things flow better.

**Comment by markalolo** [comment]
Hi @linearcombination , here's my initial inputs on the simplified version:

[A screenshot of a computer  Description automatically generated with medium confidence]


[A screenshot of a computer  Description automatically generated with medium confidence]

**Comment by markalolo** [comment]
I'd also like to see the entire language/resource line grayed so I know I can click the words and not just the check box.

This is also a case of not necessarily knowing what I want until I see it. I'm hoping Thomas or Dian will have a chance to look at it and give it their professional makeover now that it's more fully formed.

**Comment by markalolo** [comment]
Here's my inputs on the Full Version:
[A screenshot of a computer  Description automatically generated with medium confidence]

[A screenshot of a computer screen  Description automatically generated with low confidence]

**Comment by markalolo** [comment]
I'm also thinking about how to better surface these formatting options. We have had some users complain that they didn't know what to do once they got the HTML. They had to hunt around to find the settings tab.

I think this should be the default:

***@***.***

If we default to Print Optimization off, with Generate PDF on, it delivers this as the results screen.

***@***.***

This gives users the option of PDF and HTML without having to select any other choices.

**Comment by markalolo** [comment]
From @abycurley: If I understand correctly, you're saying Print Optimization should be OFF. Don't we want to make these documents as printer-friendly as possible? (In this case, less paper.)

**Comment by markalolo** [comment]
I agree we want them to be printer friendly, but the current iteration of that creates ugly documents that are hard to read. I'd like to get back to the drawing board on what a print friendly layout looks like. I'd also like to work with our internal staff on how to use Docx to control how print friendly a document is, rather than PDF where we're locked into whatever comes out.

For example here is Luke ULB w/Commentary, weighing in at 164 pages:
***@***.***

Here's Luke ULB w/Commentary "regular" not-compact, only a few pages longer at 171:
***@***.***

The compact version isn't legible due to what it gives up to save pages. We just need to do a bit more design work on it.

**Comment by abycurley** [comment]
Love it. Thanks for the explanation.

**Comment by markalolo** [comment]
By way of update -- yesterday Dian presented a new Wizard Flow which looks great. There are a few more tweaks to complete it and that design should be ready for @linearcombination  to being implementation on after 7/10.
