### ISSUE TITLE
Problem with Aushi Luke in Docx

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#127]
I requested an interleave of Aushi and English, just the scripture, as Word Doc. The Word Doc has some issues with the chapter heading rendering. It doesn't have this issue with PDF.

![image](https://user-images.githubusercontent.com/12574715/236476281-b30b9978-0da5-45ab-8735-ce397267f220.png)
[auh-reg-luk_en-ulb-wa-luk_lbo_1c_chapter.docx](https://github.com/WycliffeAssociates/DOC/files/11406853/auh-reg-luk_en-ulb-wa-luk_lbo_1c_chapter.docx)

**Comment by linearcombination** [comment]
Note to self: Aushi is one of several thousand languages which has USFM which does not conform to the spec that the USFM parser we use expects. DOC itself saves this by adding the missing bits of USFM markup the parser requires (as it does for thousands of other languages). Further,  the Aushi USFM violates the USFM standard in at least one way: \c elements are to occur on there own line and they do not for the book of Luke at least. The resulting intermediate HTML file created by the USFM parser has an additional defect: it starts with a div which is never closed at the end. This may also be true of other languages too, but just noting it here for later recall. The resulting HTML file is composed of that start div which is never closed then, despite the USFM \c markers not being on their own line, h2 HTML chapter headings are successfully created (which just demonstrates that the USFM parser we use is ok with relaxing that \c requirement) followed by the chapters verses which consist of only verse numbers in spans and all other text not contained in an element excepting (by mistake) only the initial div which is never closed. The third party library html2docx then parses the resulting HTML string into another HTML document using Python’s native html.parser module. Composer, from the docxcompose library which is a sub-library of python-docx then takes the result and converts each HTML structure into its choice of equivalent Word structure. Given this and the fact that we have only seen this so far on languages which have malformed or potentially malformed USFM means that the issue may lie in the USFM content. However the unclosed div produced by the initial parser pass over the USFM could be the issue. If that defect is not seen in languages not exhibiting this bug then it could be a usfm_tools library bug (not likely). Further, it could also be that though the resulting HTML prior to handing to the hd2 module in htmldocx library is technically valid, it may not be in a form that that python-docx is happy with when hd2 module delegates to it.  More investigation to follow a week from now.

**Comment by linearcombination** [comment]
Potentially hundreds or thousands of languages experienced this same defect. It is now fixed and deployed.
