### ISSUE TITLE
Make limit TW words toggle in backend

### ISSUE THREAD

**Issue by linearcombination** [WycliffeAssociates/DOC#130]
Make limit TW words toggle in backend by adding it as a property of DocumentRequest class

**Comment by linearcombination** [comment]
Note that this is not UI related, this does not add a toggle to the UI, this is not something you can see or be aware of as a non-developer. This is just necessary to later support a UI toggle if we decide to add that as part of UI redesign. It does however make it available through the backend API now.

**Comment by markalolo** [comment]
OK great, thanks for the update Lang.
