### ISSUE TITLE
Consider adding toggle for TN book intro inclusion to UI

### ISSUE THREAD

**Issue by linearcombination** [WycliffeAssociates/DOC#132]
Presupposes backend support first which is covered by Issue #121

**Comment by markalolo** [comment]
This can stay sitting in the backlog. It's low priority and may end up being irrelevant.

**Comment by linearcombination** [comment]
Just a note to say that this is supported in the backend and is currently just defaulted to not include the intros since it sounded like Aby didn't want them for some reason. If we did want to add such a UI control, it would be simple. Just an FYI.
