### ISSUE TITLE
Fix regression where assembly_layout_kind defaulting caused skipping selection of assembly layout kind algo

### ISSUE THREAD

**Issue by linearcombination** [WycliffeAssociates/DOC#136]
Background: DOC is designed so that the user doesn't choose the assembly layout  (different from assembly strategy which is language book order or book language order), the system chooses the assembly layout using its own algorithm based on the user's document request instance values chosen. DOC was designed, however, to at the same time allow tests to specify an arbitrary, i.e., not chosen by DOC's layout algo, assembly layout. 

The system detected if the document request came from a test by checking if the assembly layout kind was set (which the UI does not set) and simply returning it if set.

How bug arose: subsequently, a change was made wherein assembly layout kind was defaulted to 'one column'. This change meant that all requests, whether coming from tests or the UI, were skipping DOC's assembly layout algorithm therefore always just returning the default: one column. This was noticed when choosing print layout had no effect on output.

**Comment by markalolo** [comment]
I'm not sure how to test this so I'll mark it as complete.
