### ISSUE TITLE
Arabic does not render RTL properly

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#150]
Arabic ( https://content.bibletranslationtools.org/WA-Catalog/arb_nav/src/branch/master/manifest.yaml ) should render RTL but it doesn't respect the flag in the manifest that states that. It's in the JSON as "Direction"

Here's an example of rendered output:

https://doc-files-dev.walink.org/arb-nav-mrk_arb-tw-mrk_lbo_1c_chapter.html

**Comment by markalolo** [comment]
RTL is Right to Left. Here's data from the Manifest.

dublin_core:
  type: 'bundle'
  conformsto: 'rc0.2'
  format: 'text/usfm'
  identifier: 'nav'
  title: 'New Arabic Version (Ketab El Hayat)'
  subject: 'Bible'
  description: ""
  language:
    identifier: 'arb'
    title: 'العربية'
    direction: 'rtl'

**Comment by linearcombination** [comment]
Accidentally closed this. Reopened. Unintentional.
