### ISSUE TITLE
English/Amharic Word Docs missing English

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#165]
This issue seems to affect only Word docs. Combined English/Amharic results in only Amharic. Confirmed on both ULB/ULB and ULB/Notes. Samples attached.
[am-ulb-luk_am-ulb-act_en-ulb-wa-luk_en-ulb-wa-act_lbo_1c_chapter_ltwt.docx](https://github.com/WycliffeAssociates/DOC/files/12337862/am-ulb-luk_am-ulb-act_en-ulb-wa-luk_en-ulb-wa-act_lbo_1c_chapter_ltwt.docx)
[am-tn-luk_am-ulb-luk_am-tn-act_am-ulb-act_en-ulb-wa-luk_en-tn-wa-luk_en-ulb-wa-act_en-tn-wa-act_lbo_1c_c_chapter_ltwt.docx](https://github.com/WycliffeAssociates/DOC/files/12337863/am-tn-luk_am-ulb-luk_am-tn-act_am-ulb-act_en-ulb-wa-luk_en-tn-wa-luk_en-ulb-wa-act_en-tn-wa-act_lbo_1c_c_chapter_ltwt.docx)

**Comment by linearcombination** [comment]
This resolved with the latest update
