### ISSUE TITLE
No Fonts on Chinese PDFs

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#166]
Attempted to create Chinese NT with Notes, no fonts rendered in PDF. I'm aware that DOCX would need locally installed fonts but thought that PDF was created with embedded fonts. Is there a way to include fonts for non-roman languages?

**Comment by linearcombination** [comment]
This is a duplicate issue of: https://github.com/WycliffeAssociates/DOC/issues/155, but thank you! Can you please close this one.
