### ISSUE TITLE
Add Condensed NT TN to IRG

### ISSUE THREAD

**Issue by abycurley** [WycliffeAssociates/DOC#178]
Our team is getting ready to finish paring down the English NT TN with the express intent of making printing less painful. How can we get these integrated into the IRG/DOC as the default?

They're currently housed here: [https://content.bibletranslationtools.org/WycliffeAssociates/en_tn_condensed/src/branch/June_2023](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcontent.bibletranslationtools.org%2FWycliffeAssociates%2Fen_tn_condensed%2Fsrc%2Fbranch%2FJune_2023&data=05%7C01%7Caby_curley%40wycliffeassociates.org%7C08e624de964f4b8787aa08dbafbb2ee5%7C7baa11086adb4be299cf00a4872ab1cf%7C0%7C0%7C638296990721630173%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XAovzM1HmAzIHa3m%2F6aeTBucDqtBDfi9pXs1438IanE%3D&reserved=0)

**Comment by linearcombination** [comment]
I can integrate that and will start testing that to see if I can get it integrated. Thanks for the heads up and for the work

**Comment by linearcombination** [comment]
@abycurley The easiest approach to this is to create a new branch off your master branch and give it a new name, like master-archive or something, then merge your condensed version into master. Git is awesome at stuff like this. If you do this you have achieved two goals:

1. Preserve master (under a new name)
2. Make condensed TN your default

Please let me know if you have any questions or need more clarification.
