### ISSUE TITLE
Docx seems to accomodate only one book

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#180]
I'm consistently getting an issue when requesting a Docx with two languages and multiple books. The Docx stops after one book. Observed on:

Amharic/English ULB/Notes Luke/Acts
Aushi/English ULB Mat/Mrk/Luk/Jhn/Acts

I'd like to deploy the current changes to Prod but this is a stopper for me. Once this is resolved I'm excited to get this round of changes deployed for public use.

**Comment by linearcombination** [comment]
I see this, thank you. Note to self: This is manifested only when 'separate' grouping strategy is chosen and not when 'mix' grouping strategy is chosen
