### ISSUE TITLE
Issue with Email Attachment action

### ISSUE THREAD

**Issue by PurpleGuitar** [WycliffeAssociates/DOC#186]
From Chuck Liesch: The "Email me a copy of my attachment" under the notification button doesn't seem to work.

**Comment by linearcombination** [comment]
Please ensure that env vars are being properly set to currently valid values on deployment as set in docker-compose.yml

      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
      SMTP_HOST: ${SMTP_HOST}
      SEND_EMAIL: ${SEND_EMAIL}

The values may not have been set, or, the values may not be valid/current.
