### ISSUE TITLE
Spanish resources missing

### ISSUE THREAD

**Issue by PurpleGuitar** [WycliffeAssociates/DOC#192]
Report from John Wood:

I've got a report from the field that the Spanish resources (Notes, Questions, and Words) are not available for Spanish at https://doc.bibleineverylanguage.org/

I confirmed on 2024-02-21:

![image](https://github.com/WycliffeAssociates/DOC/assets/1095575/8d338203-b382-4aa9-83d1-1d24fbdf58f5)

**Comment by mondele** [comment]
I have also confirmed with French — no resources.

**Comment by linearcombination** [comment]
Latest update fixes this issue, thanks for reporting!
