### ISSUE TITLE
Increase size of TN Note Headings

### ISSUE THREAD

**Issue by PurpleGuitar** [WycliffeAssociates/DOC#193]
From Susan Quigley:

When the DOC Scripture Downloader generates PDFs of the Translation Notes, the heading for each verse note is smaller than the note text. (I put green lines next to the headings.) Could the heading be larger and the note smaller?

![image](https://github.com/WycliffeAssociates/DOC/assets/1095575/061c057e-bcb2-4a7d-9f31-f71f711a073a)

These headings are the lines in the verse notes that start with #. 

![image](https://github.com/WycliffeAssociates/DOC/assets/1095575/deb80446-ca53-4a71-a6d3-ae59991f6938)

**Comment by linearcombination** [comment]
The example notes are from a Translation notes book intro. The content team asked us to remove book intros from documents going forward so this is something you probably won't see anymore. I couldn't see it exhibited in the chapter level translations notes, they seem to have "better" formatting hierarchy. I have changed the code that controls the formatting of book intros just in case they ever come back though.
