### ISSUE TITLE
Two column layout, scripture and notes side by side

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#96]
Aaron Brakefield: Translators don't want the flipping of pages to see the notes. However, on separate pages they feel it will be lost and/or discarded. They thought maybe a landscape orientation or columns would be good. Mark, I'm imagining the formatting headache that would be to try to match source text with resource content considering the variable sizes. I don't know how you could write a script so that the notes are always on the same page in a separate column parallel to the source text.

**Comment by abycurley** [comment]
I believe Aaron has backed away from this request, as it messes with steps 1-4 of MAST. I has asked him to confirm my understanding.

**Comment by markalolo** [comment]
I'm going to close this as "Not Planned" I agree it's not a good idea at this time.
