### ISSUE TITLE
Page Break per Chapter

### ISSUE THREAD

**Issue by markalolo** [WycliffeAssociates/DOC#97]
Aaron Brakefield: We would definitely like to be able to include a page break separating the chapters so that when we print it will all be divided and easily distributed. Mark, as I did my own manual page breaks, I discovered a possible issue. If I'm printing front and back the page break could end on the front of a page and the next chapter starts on the back of that same page.

**Comment by linearcombination** [comment]
We will need to decide if we support two-sided printing as this would indeed greatly complicate things for the reason cited above.

**Comment by markalolo** [comment]
I think we should "support" two sided printing from the perspective that users will make their own choices about that, and have to live with how it prints if there's page breaks that aren't where they want them. The Word doc will allow a user to adjust as they wish. We don't need to do all those calculations during the creation of the document.

**Comment by linearcombination** [comment]
Can you confirm if this is only related to Docx or are chapter breaks wanted in PDF too?

**Comment by markalolo** [comment]
Both please, if possible.
